version: "3.9"

services:
  innostore:
    image: innostore
    build:
      context: .
      dockerfile: InnoStore/Dockerfile
    container_name: innostore
    depends_on:
      - innostore-db
    env_file:
      - .env
    environment:
      ConnectionStrings__DefaultConnection: "Host=${DB_HOST:-innostore-db};Port=${POSTGRES_PORT:-5432};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      DB_HOST: innostore-db
      DB_PORT: ${POSTGRES_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      MINIO__SpaceUrl: "http://minio:9000" 
      MINIO__AccessKey: ${MINIO_User}
      MINIO__SecretKey: ${MINIO_Password}
      MINIO__BucketName: ${MINIO_Default_Bucket}
      MINIO__EnvironmentSubFolder: ${MINIO_Environment_Sub_Folder}
      KAFKA__Server: kafka:${KAFKA_PORT}
      KAFKA__GroupId: ${KAFKA_INNOSTORE_GROUP_ID}
      KAFKA__EventsTopic: ${KAFKA_EVENTS_TOPIC}
      KAFKA__EventsDlqTopic: ${KAFKA_EVENTS_DLQ_TOPIC}
    networks:
      - innostore-net
    ports:
      - "${APP_PORT}:8080"

  innostore-db:
    image: postgres:15
    container_name: innostore-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - innostore-pg-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - innostore-net

  minio:
    image: minio/minio:latest
    container_name: blobStorage
    restart: unless-stopped
    command: server /data --console-address ":9001"
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_User}
      MINIO_ROOT_PASSWORD: ${MINIO_Password}
    volumes:
      - minio-data:/data
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    networks:
      - innostore-net

volumes:
  innostore-pg-data:
  minio-data:
  kafka-data:

networks:
  innostore-net:
    driver: bridge
