version: "3.9"

services:
  innostore:
    image: innostore
    build:
      context: .
      dockerfile: InnoStore/Dockerfile
    container_name: innostore
    depends_on:
      - innostore-db
    env_file:
      - .env
    environment:
      ConnectionStrings__DefaultConnection: "Host=${DB_HOST:-innostore-db};Port=${POSTGRES_PORT:-5432};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      DB_HOST: innostore-db
      DB_PORT: ${POSTGRES_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KAFKA__Server: kafka:${KAFKA_PORT}
      KAFKA__GroupId: ${KAFKA_INNOSTORE_GROUP_ID}
      KAFKA__EventsTopic: ${KAFKA_EVENTS_TOPIC}
      KAFKA__EventsDlqTopic: ${KAFKA_EVENTS_DLQ_TOPIC}
    networks:
      - innostore-net
    ports:
      - "${APP_PORT}:8080"

  innostore-db:
    image: postgres:15
    container_name: innostore-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - innostore-pg-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - innostore-net

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    restart: unless-stopped
    ports:
      - "${KAFKA_PORT}:9094"
    volumes:
      - kafka-data:/apache/kafka
    env_file:
      - .env
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:${KAFKA_PORT},CONTROLLER://0.0.0.0:${KAFKA_CONTROLLER_PORT}
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://${KAFKA_EXTERNAL_SERVER}:${KAFKA_PORT}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:${KAFKA_CONTROLLER_PORT}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - innostore-net

  init-kafka:
    image: apache/kafka:latest
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      echo -e 'Waiting for Kafka to be ready...'
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list

      echo -e 'Creating kafka topics...'
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --topic ${KAFKA_EVENTS_TOPIC} --partitions 2 --replication-factor 1 --if-not-exists
      
      echo -e 'Successfully created the following topics:'
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list
      "
    networks:
      - innostore-net

volumes:
  innostore-pg-data:
  kafka-data:

networks:
  innostore-net:
    driver: bridge
